---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: code-server-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`code.skynetsystems.io`)
    services:
    - name: code-server-service
      port: 8080
  tls:
    passthrough: true
