apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls-secret
  dnsNames:
    - vault.skynetsystems.io
    - vault-api.skynetsystems.io
    - vault-0.vault-internal
    - vault-1.vault-internal
    - vault-2.vault-internal
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: vault-ca-issuer 
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
