apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@skynetsystems.io
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
      - dns01:
          cloudflare:
            email: you@example.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "example.com"
