apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  annotations:
    kapp.k14s.io/identity: v1;/carto.run/ClusterSupplyChain/scanning-image-scan-to-url;carto.run/v1alpha1
  name: scanning-image-scan-to-url
spec:
  params:
  - default: "-----BEGIN CERTIFICATE-----\nMIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh\nMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\nd3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD\nQTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT\nMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j\nb20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB\nCSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97\nnh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt\n43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P\nT19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4\ngdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO\nBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR\nTLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw\nDQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr\nhMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg\n06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF\nPnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls\nYSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk\nCAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=\n-----END
      CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIFajCCBPGgAwIBAgIQDNCovsYyz+ZF7KCpsIT7HDAKBggqhkjOPQQDAzBWMQsw\nCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMTAwLgYDVQQDEydEaWdp\nQ2VydCBUTFMgSHlicmlkIEVDQyBTSEEzODQgMjAyMCBDQTEwHhcNMjMwMjE0MDAw\nMDAwWhcNMjQwMzE0MjM1OTU5WjBmMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2Fs\naWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEVMBMGA1UEChMMR2l0SHVi\nLCBJbmMuMRMwEQYDVQQDEwpnaXRodWIuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D\nAQcDQgAEo6QDRgPfRlFWy8k5qyLN52xZlnqToPu5QByQMog2xgl2nFD1Vfd2Xmgg\nnO4i7YMMFTAQQUReMqyQodWq8uVDs6OCA48wggOLMB8GA1UdIwQYMBaAFAq8CCkX\njKU5bXoOzjPHLrPt+8N6MB0GA1UdDgQWBBTHByd4hfKdM8lMXlZ9XNaOcmfr3jAl\nBgNVHREEHjAcggpnaXRodWIuY29tgg53d3cuZ2l0aHViLmNvbTAOBgNVHQ8BAf8E\nBAMCB4AwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMIGbBgNVHR8EgZMw\ngZAwRqBEoEKGQGh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRMU0h5\nYnJpZEVDQ1NIQTM4NDIwMjBDQTEtMS5jcmwwRqBEoEKGQGh0dHA6Ly9jcmw0LmRp\nZ2ljZXJ0LmNvbS9EaWdpQ2VydFRMU0h5YnJpZEVDQ1NIQTM4NDIwMjBDQTEtMS5j\ncmwwPgYDVR0gBDcwNTAzBgZngQwBAgIwKTAnBggrBgEFBQcCARYbaHR0cDovL3d3\ndy5kaWdpY2VydC5jb20vQ1BTMIGFBggrBgEFBQcBAQR5MHcwJAYIKwYBBQUHMAGG\nGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBPBggrBgEFBQcwAoZDaHR0cDovL2Nh\nY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VExTSHlicmlkRUNDU0hBMzg0MjAy\nMENBMS0xLmNydDAJBgNVHRMEAjAAMIIBgAYKKwYBBAHWeQIEAgSCAXAEggFsAWoA\ndwDuzdBk1dsazsVct520zROiModGfLzs3sNRSFlGcR+1mwAAAYZQ3Rv6AAAEAwBI\nMEYCIQDkFq7T4iy6gp+pefJLxpRS7U3gh8xQymmxtI8FdzqU6wIhALWfw/nLD63Q\nYPIwG3EFchINvWUfB6mcU0t2lRIEpr8uAHYASLDja9qmRzQP5WoC+p0w6xxSActW\n3SyB2bu/qznYhHMAAAGGUN0cKwAABAMARzBFAiAePGAyfiBR9dbhr31N9ZfESC5G\nV2uGBTcyTyUENrH3twIhAPwJfsB8A4MmNr2nW+sdE1n2YiCObW+3DTHr2/UR7lvU\nAHcAO1N3dT4tuYBOizBbBv5AO2fYT8P0x70ADS1yb+H61BcAAAGGUN0cOgAABAMA\nSDBGAiEAzOBr9OZ0+6OSZyFTiywN64PysN0FLeLRyL5jmEsYrDYCIQDu0jtgWiMI\nKU6CM0dKcqUWLkaFE23c2iWAhYAHqrFRRzAKBggqhkjOPQQDAwNnADBkAjAE3A3U\n3jSZCpwfqOHBdlxi9ASgKTU+wg0qw3FqtfQ31OwLYFdxh0MlNk/HwkjRSWgCMFbQ\nvMkXEPvNvv4t30K6xtpG26qmZ+6OiISBIIXMljWnsiYR1gyZnTzIg3AQSw4Vmw==\n-----END
      CERTIFICATE----- \n    \n"
    name: ca_cert_data
  - default: main
    name: gitops_branch
  - default: supplychain
    name: gitops_user_name
  - default: supplychain
    name: gitops_user_email
  - default: supplychain@cluster.local
    name: gitops_commit_message
  - default: ""
    name: gitops_ssh_secret
  - default: ssh://git@github.com
    name: gitops_server_address
  - default: pivotal-ben-chacko
    name: gitops_repository_owner
  - default: delivery
    name: gitops_repository_name
  - default: github
    name: gitops_server_kind
  - default: dev
    name: gitops_commit_branch
  - default: ready for review
    name: gitops_pull_request_title
  - default: generated by supply chain
    name: gitops_pull_request_body
  - name: image_scanning_service_account_publisher
    value: default
  - default: default
    name: image_scanning_service_account_scanner
  - name: image_scanning_cli
    value:
      image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:9ef533905d900ccb86883eeb78843b965be685f8d7e7c31066b4b1d8d383ab41
  - default: 4Gi
    name: image_scanning_workspace_size
  - name: image_scanning_active_keychains
    value: []
  resources:
  - name: image-provider
    params:
    - default: default
      name: serviceAccount
    templateRef:
      kind: ClusterImageTemplate
      name: image-provider-template
  - images:
    - name: image
      resource: image-provider
    name: image-scanner
    params:
    - default: scan-policy
      name: scanning_image_policy
    - default: private-image-scan-template
      name: scanning_image_template
    - name: registry
      value:
        ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIDKDCCAhCgAwIBAgIQeB+bKA5ZTHU9Tr6d2wVtszANBgkqhkiG9w0BAQsFADAU
          MRIwEAYDVQQDEwlIYXJib3IgQ0EwHhcNMjMxMjExMTUxNTU1WhcNMzMxMjA4MTUx
          NTU1WjAUMRIwEAYDVQQDEwlIYXJib3IgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
          DwAwggEKAoIBAQDQxXPX/UlTBHGqi2Iz8FF99ekXGwoLfEPxeW1jykoTZr/lAL/t
          3iLnXxF13pVu4hv7SpEt0eJjCc60vInsQk8ZFvE0QEaCgFt6FgHqas+NbXrnfDTW
          oc4iKuZH3Ps75ClBtl1K0EIg+dOI/7t+JVQ5XsLl4BgcZMvoruyTxHLdCJPHKX/r
          UtusQBaMZlcqk8Uy93su4UBCzrM7YTInraFivFOf1buFacWwWXbeLWp2Si73LlDB
          oF3mdSWGbRSyWk9SyRct+ISG+Iuhmai0gsmqcecaR3D6fuGtmzr7bWOeQvlFfyGm
          8o59Mu2C7gV33lk8v8GjAb1u1NKJ8mxLsVqfAgMBAAGjdjB0MA4GA1UdDwEB/wQE
          AwICBDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUw
          AwEB/zAdBgNVHQ4EFgQUfSOyfEd1dcZTuBKt5QlAvNaYNiswEwYDVR0RBAwwCoII
          aGFyYm9yY2EwDQYJKoZIhvcNAQELBQADggEBAEWkyLaO5DYe8irPhTVYgfvgmXYH
          7T65B4b87JeCO8YoXq111z7t8XxCqkK9QDqTDLs38V5LF4/g8TVcvggAv690GL/Z
          wz3W20lnpX/0j+S4pxNlgzpAh/B4GmnkwhCpl6XmIiQke9UcFUsNTzlu9FLQucDq
          BEah1hkFWnCOul+uhybya5TlQQeS2I9G489buwcHemgyLoockH90uAF5wdCGnVsc
          BJMYlHhw3ZLlIDgcX2LSXVeOG+jnd+K0/T72oulMVemAMteXoob4qlOTdbVpeCSH
          nTImNOEro/rB2/HUewQiVJVERGOzRK6NIZCs4U279pB2mt5WBDhDJRIWABY=
          -----END CERTIFICATE-----
        repository: tap/workloads
        server: harbor.skynetsystems.io
    templateRef:
      kind: ClusterImageTemplate
      name: image-scanner-template
  - images:
    - name: image
      resource: image-scanner
    name: config-provider
    params:
    - default: default
      name: serviceAccount
    templateRef:
      kind: ClusterConfigTemplate
      name: convention-template
  - configs:
    - name: config
      resource: config-provider
    name: app-config
    templateRef:
      kind: ClusterConfigTemplate
      options:
      - name: config-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: web
      - name: server-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: server
      - name: worker-template
        selector:
          matchLabels:
            apps.tanzu.vmware.com/workload-type: worker
  - configs:
    - name: app_def
      resource: app-config
    name: service-bindings
    templateRef:
      kind: ClusterConfigTemplate
      name: service-bindings
  - configs:
    - name: app_def
      resource: service-bindings
    name: api-descriptors
    templateRef:
      kind: ClusterConfigTemplate
      name: api-descriptors
  - configs:
    - name: config
      resource: api-descriptors
    name: config-writer
    params:
    - default: default
      name: serviceAccount
    - name: registry
      value:
        ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIDKDCCAhCgAwIBAgIQeB+bKA5ZTHU9Tr6d2wVtszANBgkqhkiG9w0BAQsFADAU
          MRIwEAYDVQQDEwlIYXJib3IgQ0EwHhcNMjMxMjExMTUxNTU1WhcNMzMxMjA4MTUx
          NTU1WjAUMRIwEAYDVQQDEwlIYXJib3IgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
          DwAwggEKAoIBAQDQxXPX/UlTBHGqi2Iz8FF99ekXGwoLfEPxeW1jykoTZr/lAL/t
          3iLnXxF13pVu4hv7SpEt0eJjCc60vInsQk8ZFvE0QEaCgFt6FgHqas+NbXrnfDTW
          oc4iKuZH3Ps75ClBtl1K0EIg+dOI/7t+JVQ5XsLl4BgcZMvoruyTxHLdCJPHKX/r
          UtusQBaMZlcqk8Uy93su4UBCzrM7YTInraFivFOf1buFacWwWXbeLWp2Si73LlDB
          oF3mdSWGbRSyWk9SyRct+ISG+Iuhmai0gsmqcecaR3D6fuGtmzr7bWOeQvlFfyGm
          8o59Mu2C7gV33lk8v8GjAb1u1NKJ8mxLsVqfAgMBAAGjdjB0MA4GA1UdDwEB/wQE
          AwICBDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUw
          AwEB/zAdBgNVHQ4EFgQUfSOyfEd1dcZTuBKt5QlAvNaYNiswEwYDVR0RBAwwCoII
          aGFyYm9yY2EwDQYJKoZIhvcNAQELBQADggEBAEWkyLaO5DYe8irPhTVYgfvgmXYH
          7T65B4b87JeCO8YoXq111z7t8XxCqkK9QDqTDLs38V5LF4/g8TVcvggAv690GL/Z
          wz3W20lnpX/0j+S4pxNlgzpAh/B4GmnkwhCpl6XmIiQke9UcFUsNTzlu9FLQucDq
          BEah1hkFWnCOul+uhybya5TlQQeS2I9G489buwcHemgyLoockH90uAF5wdCGnVsc
          BJMYlHhw3ZLlIDgcX2LSXVeOG+jnd+K0/T72oulMVemAMteXoob4qlOTdbVpeCSH
          nTImNOEro/rB2/HUewQiVJVERGOzRK6NIZCs4U279pB2mt5WBDhDJRIWABY=
          -----END CERTIFICATE-----
        repository: tap/workloads
        server: harbor.skynetsystems.io
    templateRef:
      kind: ClusterTemplate
      name: config-writer-and-pull-requester-template
  - name: deliverable
    params:
    - name: registry
      value:
        ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIDKDCCAhCgAwIBAgIQeB+bKA5ZTHU9Tr6d2wVtszANBgkqhkiG9w0BAQsFADAU
          MRIwEAYDVQQDEwlIYXJib3IgQ0EwHhcNMjMxMjExMTUxNTU1WhcNMzMxMjA4MTUx
          NTU1WjAUMRIwEAYDVQQDEwlIYXJib3IgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
          DwAwggEKAoIBAQDQxXPX/UlTBHGqi2Iz8FF99ekXGwoLfEPxeW1jykoTZr/lAL/t
          3iLnXxF13pVu4hv7SpEt0eJjCc60vInsQk8ZFvE0QEaCgFt6FgHqas+NbXrnfDTW
          oc4iKuZH3Ps75ClBtl1K0EIg+dOI/7t+JVQ5XsLl4BgcZMvoruyTxHLdCJPHKX/r
          UtusQBaMZlcqk8Uy93su4UBCzrM7YTInraFivFOf1buFacWwWXbeLWp2Si73LlDB
          oF3mdSWGbRSyWk9SyRct+ISG+Iuhmai0gsmqcecaR3D6fuGtmzr7bWOeQvlFfyGm
          8o59Mu2C7gV33lk8v8GjAb1u1NKJ8mxLsVqfAgMBAAGjdjB0MA4GA1UdDwEB/wQE
          AwICBDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUw
          AwEB/zAdBgNVHQ4EFgQUfSOyfEd1dcZTuBKt5QlAvNaYNiswEwYDVR0RBAwwCoII
          aGFyYm9yY2EwDQYJKoZIhvcNAQELBQADggEBAEWkyLaO5DYe8irPhTVYgfvgmXYH
          7T65B4b87JeCO8YoXq111z7t8XxCqkK9QDqTDLs38V5LF4/g8TVcvggAv690GL/Z
          wz3W20lnpX/0j+S4pxNlgzpAh/B4GmnkwhCpl6XmIiQke9UcFUsNTzlu9FLQucDq
          BEah1hkFWnCOul+uhybya5TlQQeS2I9G489buwcHemgyLoockH90uAF5wdCGnVsc
          BJMYlHhw3ZLlIDgcX2LSXVeOG+jnd+K0/T72oulMVemAMteXoob4qlOTdbVpeCSH
          nTImNOEro/rB2/HUewQiVJVERGOzRK6NIZCs4U279pB2mt5WBDhDJRIWABY=
          -----END CERTIFICATE-----
        repository: tap/workloads
        server: harbor.skynetsystems.io
    - default: go-git
      name: gitImplementation
    templateRef:
      kind: ClusterTemplate
      name: deliverable-template
  selectorMatchExpressions:
  - key: apps.tanzu.vmware.com/workload-type
    operator: In
    values:
    - web
    - server
    - worker
  selectorMatchFields:
  - key: spec.image
    operator: Exists
