---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tap-go-test-pipeline
  namespace: dev
  labels:
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/language: go
spec:
  params:
    - name: source-url                        # (!) required
    - name: source-revision                   # (!) required
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: golang
            script: |-
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz -m
              cd go
              go test -v .
