---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxx
  namespace: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  rules:
    - host: nginx.skynetsystems.io 
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
            path: /
  tls:
    - hosts:
      - nginx.skynetsystems.io
      secretName: nginx-ingress-tls
