apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 4
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: mop
        image: beninaskaria/vmware:spring-demo
