namespace: tanzu-system-registry
hostname: harbor.skynetsystems.io
port:
  https: 443
logLevel: info
tlsCertificate:
  tls.crt:
  tls.key:
  ca.crt:
  tlsSecretLabels:
tlsCertificateSecretName:
enableContourHttpProxy: true
contourHttpProxy:
  timeout: 0s
  idleTimeout: 5m
harborAdminPassword: changeme
secretKey: k3rhWrZ4jmOTCtUU
database:
  password: Qg5teGMNbc4jB6Ns
  shmSizeLimit:
  maxIdleConns:
  maxOpenConns:
exporter:
  cacheDuration:
core:
  replicas: 1
  secret: utV1IVOOKGPPqBB6
  xsrfKey: GKIi3nv3JPbq96X5LzhQzpyA1C9MN9ax
jobservice:
  replicas: 1
  secret: gnKLd1BK4NX7kOSU
registry:
  replicas: 1
  secret: 1d9a9UppphZthesn
notary:
  enabled: true
trivy:
  enabled: true
  replicas: 1
  gitHubToken: ""
  skipUpdate: false
  offlineScan: false
  timeout:
persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 20Gi
    jobservice:
      jobLog:
        existingClaim: ""
        storageClass: ""
        subPath: ""
        accessMode: ReadWriteOnce
        size: 1Gi
    database:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    redis:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
    trivy:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
  imageChartStorage:
    disableredirect: false
    type: filesystem
    filesystem:
      rootdirectory: /storage
    azure:
      accountname: accountname
      accountkey: base64encodedaccountkey
      container: containername
      realm: core.windows.net
    gcs:
      bucket: bucketname
      encodedkey: base64-encoded-json-key-file
      rootdirectory: null
      chunksize: 5242880
    s3:
      region: us-west-1
      bucket: bucketname
      accesskey: null
      secretkey: null
      regionendpoint: null
      encrypt: false
      keyid: null
      secure: true
      skipverify: false
      v4auth: true
      chunksize: null
      rootdirectory: null
      storageclass: STANDARD
      multipartcopychunksize: null
      multipartcopymaxconcurrency: null
      multipartcopythresholdsize: null
    swift:
      authurl: https://storage.myprovider.com/v3/auth
      username: username
      password: password
      container: containername
      region: null
      tenant: null
      tenantid: null
      domain: null
      domainid: null
      trustid: null
      insecureskipverify: null
      chunksize: null
      prefix: null
      secretkey: null
      accesskey: null
      authversion: null
      endpointtype: null
      tempurlcontainerkey: null
      tempurlmethods: null
    oss:
      accesskeyid: accesskeyid
      accesskeysecret: accesskeysecret
      region: regionname
      bucket: bucketname
      endpoint: null
      internal: null
      encrypt: null
      secure: null
      chunksize: null
      rootdirectory: null
proxy:
  httpProxy:
  httpsProxy:
  noProxy: 127.0.0.1,localhost,.local,.internal
pspNames: null
caBundleSecretName:
metrics:
  enabled: false
  core:
    path: /metrics
    port: 8001
  registry:
    path: /metrics
    port: 8001
  jobservice:
    path: /metrics
    port: 8001
  exporter:
    path: /metrics
    port: 8001
network:
  ipFamilies: []
trace:
  enabled: false
  provider: jaeger
  sample_rate: 1
  namespace:
  attributes:
    application: harbor
  jaeger:
    endpoint: http://hostname:14268/api/traces
    username:
    password:
    agent_host:
    agent_port:
  otel:
    endpoint: hostname:4318
    url_path: /v1/traces
    compression: false
    insecure: true
    timeout: 10
cache:
  enabled: false
  expireHours: 24
